{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common-service.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common-service.name" . }}
    release: {{ template "common-service.releaseLabel" . }}
    {{- include "common-service.labels" . | nindent 4 }}
{{- if .Values.config.annotations }}
  annotations:
{{ toYaml .Values.config.annotations | indent 4 }}
{{- end }}
data:
{{- if .Values.config.entries }}
{{ toYaml .Values.config.entries | indent 2 }}
{{- end }}
{{- end }}