{{- $replicaCount := int .Values.deployment.replicas }}
{{- if and .Values.pdb.create (or (gt $replicaCount 1) .Values.deployment.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common-service.name" . }}
    {{- include "common-service.labels" . | nindent 4 }}
  {{- if .Values.pdb.annotations }}
  annotations:
    {{ toYaml .Values.pdb.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end  }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "common-service.selectorLabels" . | nindent 6 }}
{{- end }}
