{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common-service.name" . }}
    {{- include "common-service.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ template "common-service.name" . }}
{{- end }}