# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sample Node.js Application

on:
  workflow_dispatch:
    inputs:
      PRODUCT:
        description: "배포 대상 프로덕트"
        required: true
        type: choice
        options:
        - "auth"
        - "orders"
        - "products"
      VERSION:
        description: "배포 버전"
        required: true
        type: string

env:
  HARBOR_URL: "ops-harbor-uswe2.knowre-dev.com"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
    - name: Git Clone
      uses: actions/checkout@v3
#      with:
#        ref: ${{ inputs.VERSION }}
    - name: Login to Harbor
      uses: docker/login-action@v1
      with:
        registry: ${{ env.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Build Docker
      run: |
        cd ${{ inputs.PRODUCT }}
        export DOCKER_BUILDKIT=1
        docker build -t ${{ env.HARBOR_URL }}/ekstest/${{ inputs.PRODUCT }}:${{ inputs.VERSION }} \
        -t ${{ env.HARBOR_URL }}/ekstest/${{ inputs.PRODUCT }}:latest .
        docker push ${{ env.HARBOR_URL }}/ekstest/${{ inputs.PRODUCT }}:${{ inputs.VERSION }}
        docker push ${{ env.HARBOR_URL }}/ekstest/${{ inputs.PRODUCT }}:latest
    - name: Checkout Helm Repository
      uses: actions/checkout@v3
      with:
        repository: pascal-h-kim/helm-deploy-repo
        path: helm-deploy-repo
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
    # - name: file list
    #   run:
    #     ls -CFR
    - name: Change Helm image tag
      uses: mikefarah/yq@master
      env:
        IMAGE_TAG: ${{ inputs.VERSION }}
      with:
        cmd: yq eval -i '.sample.deployment.image.tag = env(IMAGE_TAG)' 'helm-deploy-repo/environments/dev/charts/sample-apps/${{ inputs.PRODUCT }}/values-${{ inputs.PRODUCT }}.yaml'
    # - name: View yaml
    #   run:
    #     cat helm-deploy-repo/environments/dev/charts/sample-apps/${{ inputs.PRODUCT }}/values-${{ inputs.PRODUCT }}.yaml
    - name: Push helm repo
      env:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        IMAGE_TAG: ${{ inputs.VERSION }}
      run: |
        cd helm-deploy-repo
        git config --global user.email "hyun.kim@knowre.com"
        git config --global user.name "pascal-h-kim"

        git add environments/dev/charts/sample-apps/${{ inputs.PRODUCT }}/values-${{ inputs.PRODUCT }}.yaml;
        git commit --message "Update ${{ inputs.PRODUCT }} image tag to $IMAGE_TAG";
        git push --prune 
