# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sample Node.js Application

on:
  workflow_dispatch:
    inputs:
      PRODUCT:
        description: "배포 대상 프로덕트"
        required: true
        type: choice
        options:
        - "auth"
        - "orders"
        - "products"
      VERSION:
        description: "배포 버전"
        required: true
        type: string

env:
  HARBOR_URL: "ops-harbor-uswe2.knowre-dev.com"
  HARBOR_USERNAME: "robot$sample"
  HARBOR_TOKEN: "ps9rhNK5CsdeAUqj4koJnY6TN7EzwxGr"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: read
      
    steps:
    - name: Git Clone
      uses: actions/checkout@v3
#      with:
#        ref: ${{ inputs.VERSION }}
    - name: Login to Harbor
      uses: docker/login-action@v1
      with:
        registry: ${{ env.HARBOR_URL }}
        username: ${{ env.HARBOR_USERNAME }}
        password: ${{ env.HARBOR_TOKEN }}
    - name: Build Docker
      run: |
        cd ${{ inputs.PRODUCT }}
        export DOCKER_BUILDKIT=1
        docker build -t ops-harbor-apne1.knowre-dev.com/ekstest/${{ inputs.PRODUCT }}:${{ inputs.VERSION }} \
        -t ops-harbor-apne1.knowre-dev.com/ekstest/${{ inputs.PRODUCT }}:latest .
        docker push ops-harbor-apne1.knowre-dev.com/ekstest/${{ inputs.PRODUCT }}:${{ inputs.VERSION }}
        docker push ops-harbor-apne1.knowre-dev.com/ekstest/${{ inputs.PRODUCT }}:latest
