# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Helm Update Test

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "배포 버전"
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - name: Checkout Helm Repository
      uses: actions/checkout@v3
      with:
        repository: pascal-h-kim/helm-deploy-repo
        path: helm-deploy-repo
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: file list
      run:
        ls -CFR
    - name: Change Helm image tag
      uses: mikefarah/yq@master
      env:
        IMAGE_TAG: ${{ inputs.VERSION }}
      with:
        cmd: yq eval -i '.sample.deployment.image.tag = env(IMAGE_TAG)' 'helm-deploy-repo/environments/dev/charts/sample-apps/auth/values-auth-bluegreen.yaml'
    - name: View yaml
      run:
        cat helm-deploy-repo/environments/dev/charts/sample-apps/auth/values-auth-bluegreen.yaml
    - name: Push helm repo
      env:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        IMAGE_TAG: ${{ inputs.VERSION }}
      run: |
        cd helm-deploy-repo
        git config --global user.email "hyun.kim@knowre.com"
        git config --global user.name "pascal-h-kim"

        git add environments/dev/charts/sample-apps/auth/values-auth-bluegreen.yaml;
        git commit --message "Update auth image tag to $IMAGE_TAG";
        git push --prune 
